const prJson = {
  url: "https://api.github.com/repos/rails/rails/pulls/44213",
  id: 827642516,
  node_id: "PR_kwDNIULOMVTSlA",
  html_url: "https://github.com/rails/rails/pull/44213",
  diff_url: "https://github.com/rails/rails/pull/44213.diff",
  patch_url: "https://github.com/rails/rails/pull/44213.patch",
  issue_url: "https://api.github.com/repos/rails/rails/issues/44213",
  number: 44213,
  state: "open",
  locked: false,
  title: "activesupport `Object#as_json` more thorough implicit conversion",
  user: {
    login: "notEthan",
    id: 133719,
    node_id: "MDQ6VXNlcjEzMzcxOQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/133719?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/notEthan",
    html_url: "https://github.com/notEthan",
    followers_url: "https://api.github.com/users/notEthan/followers",
    following_url:
      "https://api.github.com/users/notEthan/following{/other_user}",
    gists_url: "https://api.github.com/users/notEthan/gists{/gist_id}",
    starred_url: "https://api.github.com/users/notEthan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/notEthan/subscriptions",
    organizations_url: "https://api.github.com/users/notEthan/orgs",
    repos_url: "https://api.github.com/users/notEthan/repos",
    events_url: "https://api.github.com/users/notEthan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/notEthan/received_events",
    type: "User",
    site_admin: false,
  },
  body: "### Summary\r\n\r\ncurrently activesupport's `Object#as_json` checks if self is implicitly convertible to a hash (implicit conversion as documented at https://docs.ruby-lang.org/en/master/doc/implicit_conversion_rdoc.html ). while this makes sense and is good, it omits the other three implicit conversion that ruby documents.\r\n\r\nthis PR adds the other implicit conversions in `Object#as_json`. also, since hashlike and arraylike objects are pretty likely to be Enumerable, I also added implicit conversion of those two to `Enumerable#as_json`.\r\n\r\n(small tangent: Enumerable defines `#to_a`, and if `#to_ary` is defined as well, the difference or benefit of one over the other is questionable. `#to_ary` might be more performant, since the object would be defining that itself, whereas `Enumerable#to_a` goes through `Enumerable#each`, but that depends on the particular implementation. anyway, `#to_ary` is unlikely to be any worse, and if `#to_ary` is defined, it seems good to use it.)\r\n\r\n### Other Information\r\n\r\nI work on a library that wraps json data and adds functionality, which defines `#to_ary` and friends as appropriate. I do define an `as_json` method too, for activesupport, but for libraries that don't go out of their way for activesupport, but do support ruby-defined implicit conversion, this increases compatibility. it doesn't get all the way there, since the other basic types have no defined implicit conversion, but it helps.\r\n",
  created_at: "2022-01-20T15:20:21Z",
  updated_at: "2022-01-26T12:56:34Z",
  closed_at: null,
  merged_at: null,
  merge_commit_sha: "02d820de0a416bc1484c5707e668998ab3cb2055",
  assignee: null,
  assignees: [],
  requested_reviewers: [],
  requested_teams: [],
  labels: [
    {
      id: 107194,
      node_id: "MDU6TGFiZWwxMDcxOTQ=",
      url: "https://api.github.com/repos/rails/rails/labels/activesupport",
      name: "activesupport",
      color: "FC9300",
      default: false,
      description: null,
    },
  ],
  milestone: null,
  draft: false,
  commits_url: "https://api.github.com/repos/rails/rails/pulls/44213/commits",
  review_comments_url:
    "https://api.github.com/repos/rails/rails/pulls/44213/comments",
  review_comment_url:
    "https://api.github.com/repos/rails/rails/pulls/comments{/number}",
  comments_url:
    "https://api.github.com/repos/rails/rails/issues/44213/comments",
  statuses_url:
    "https://api.github.com/repos/rails/rails/statuses/a9d3bb1a3bd0a30f7d6fe25b6eda3ebf3ca3cd8c",
  head: {
    label: "notEthan:as_json_implicit_conversion",
    ref: "as_json_implicit_conversion",
    sha: "a9d3bb1a3bd0a30f7d6fe25b6eda3ebf3ca3cd8c",
    user: {
      login: "notEthan",
      id: 133719,
      node_id: "MDQ6VXNlcjEzMzcxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/133719?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/notEthan",
      html_url: "https://github.com/notEthan",
      followers_url: "https://api.github.com/users/notEthan/followers",
      following_url:
        "https://api.github.com/users/notEthan/following{/other_user}",
      gists_url: "https://api.github.com/users/notEthan/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/notEthan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/notEthan/subscriptions",
      organizations_url: "https://api.github.com/users/notEthan/orgs",
      repos_url: "https://api.github.com/users/notEthan/repos",
      events_url: "https://api.github.com/users/notEthan/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/notEthan/received_events",
      type: "User",
      site_admin: false,
    },
    repo: {
      id: 19901730,
      node_id: "MDEwOlJlcG9zaXRvcnkxOTkwMTczMA==",
      name: "rails",
      full_name: "notEthan/rails",
      private: false,
      owner: {
        login: "notEthan",
        id: 133719,
        node_id: "MDQ6VXNlcjEzMzcxOQ==",
        avatar_url: "https://avatars.githubusercontent.com/u/133719?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/notEthan",
        html_url: "https://github.com/notEthan",
        followers_url: "https://api.github.com/users/notEthan/followers",
        following_url:
          "https://api.github.com/users/notEthan/following{/other_user}",
        gists_url: "https://api.github.com/users/notEthan/gists{/gist_id}",
        starred_url:
          "https://api.github.com/users/notEthan/starred{/owner}{/repo}",
        subscriptions_url:
          "https://api.github.com/users/notEthan/subscriptions",
        organizations_url: "https://api.github.com/users/notEthan/orgs",
        repos_url: "https://api.github.com/users/notEthan/repos",
        events_url: "https://api.github.com/users/notEthan/events{/privacy}",
        received_events_url:
          "https://api.github.com/users/notEthan/received_events",
        type: "User",
        site_admin: false,
      },
      html_url: "https://github.com/notEthan/rails",
      description: "Ruby on Rails",
      fork: true,
      url: "https://api.github.com/repos/notEthan/rails",
      forks_url: "https://api.github.com/repos/notEthan/rails/forks",
      keys_url: "https://api.github.com/repos/notEthan/rails/keys{/key_id}",
      collaborators_url:
        "https://api.github.com/repos/notEthan/rails/collaborators{/collaborator}",
      teams_url: "https://api.github.com/repos/notEthan/rails/teams",
      hooks_url: "https://api.github.com/repos/notEthan/rails/hooks",
      issue_events_url:
        "https://api.github.com/repos/notEthan/rails/issues/events{/number}",
      events_url: "https://api.github.com/repos/notEthan/rails/events",
      assignees_url:
        "https://api.github.com/repos/notEthan/rails/assignees{/user}",
      branches_url:
        "https://api.github.com/repos/notEthan/rails/branches{/branch}",
      tags_url: "https://api.github.com/repos/notEthan/rails/tags",
      blobs_url: "https://api.github.com/repos/notEthan/rails/git/blobs{/sha}",
      git_tags_url:
        "https://api.github.com/repos/notEthan/rails/git/tags{/sha}",
      git_refs_url:
        "https://api.github.com/repos/notEthan/rails/git/refs{/sha}",
      trees_url: "https://api.github.com/repos/notEthan/rails/git/trees{/sha}",
      statuses_url:
        "https://api.github.com/repos/notEthan/rails/statuses/{sha}",
      languages_url: "https://api.github.com/repos/notEthan/rails/languages",
      stargazers_url: "https://api.github.com/repos/notEthan/rails/stargazers",
      contributors_url:
        "https://api.github.com/repos/notEthan/rails/contributors",
      subscribers_url:
        "https://api.github.com/repos/notEthan/rails/subscribers",
      subscription_url:
        "https://api.github.com/repos/notEthan/rails/subscription",
      commits_url: "https://api.github.com/repos/notEthan/rails/commits{/sha}",
      git_commits_url:
        "https://api.github.com/repos/notEthan/rails/git/commits{/sha}",
      comments_url:
        "https://api.github.com/repos/notEthan/rails/comments{/number}",
      issue_comment_url:
        "https://api.github.com/repos/notEthan/rails/issues/comments{/number}",
      contents_url:
        "https://api.github.com/repos/notEthan/rails/contents/{+path}",
      compare_url:
        "https://api.github.com/repos/notEthan/rails/compare/{base}...{head}",
      merges_url: "https://api.github.com/repos/notEthan/rails/merges",
      archive_url:
        "https://api.github.com/repos/notEthan/rails/{archive_format}{/ref}",
      downloads_url: "https://api.github.com/repos/notEthan/rails/downloads",
      issues_url: "https://api.github.com/repos/notEthan/rails/issues{/number}",
      pulls_url: "https://api.github.com/repos/notEthan/rails/pulls{/number}",
      milestones_url:
        "https://api.github.com/repos/notEthan/rails/milestones{/number}",
      notifications_url:
        "https://api.github.com/repos/notEthan/rails/notifications{?since,all,participating}",
      labels_url: "https://api.github.com/repos/notEthan/rails/labels{/name}",
      releases_url: "https://api.github.com/repos/notEthan/rails/releases{/id}",
      deployments_url:
        "https://api.github.com/repos/notEthan/rails/deployments",
      created_at: "2014-05-18T03:12:21Z",
      updated_at: "2019-09-18T06:49:21Z",
      pushed_at: "2022-01-22T09:51:40Z",
      git_url: "git://github.com/notEthan/rails.git",
      ssh_url: "git@github.com:notEthan/rails.git",
      clone_url: "https://github.com/notEthan/rails.git",
      svn_url: "https://github.com/notEthan/rails",
      homepage: "http://rubyonrails.org",
      size: 195078,
      stargazers_count: 0,
      watchers_count: 0,
      language: "Ruby",
      has_issues: false,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
        node_id: "MDc6TGljZW5zZTEz",
      },
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: "public",
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: "master",
    },
  },
  base: {
    label: "rails:main",
    ref: "main",
    sha: "77131eabc640d26a26c46d4f583f54e6db47229b",
    user: {
      login: "rails",
      id: 4223,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjQyMjM=",
      avatar_url: "https://avatars.githubusercontent.com/u/4223?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/rails",
      html_url: "https://github.com/rails",
      followers_url: "https://api.github.com/users/rails/followers",
      following_url:
        "https://api.github.com/users/rails/following{/other_user}",
      gists_url: "https://api.github.com/users/rails/gists{/gist_id}",
      starred_url: "https://api.github.com/users/rails/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/rails/subscriptions",
      organizations_url: "https://api.github.com/users/rails/orgs",
      repos_url: "https://api.github.com/users/rails/repos",
      events_url: "https://api.github.com/users/rails/events{/privacy}",
      received_events_url: "https://api.github.com/users/rails/received_events",
      type: "Organization",
      site_admin: false,
    },
    repo: {
      id: 8514,
      node_id: "MDEwOlJlcG9zaXRvcnk4NTE0",
      name: "rails",
      full_name: "rails/rails",
      private: false,
      owner: {
        login: "rails",
        id: 4223,
        node_id: "MDEyOk9yZ2FuaXphdGlvbjQyMjM=",
        avatar_url: "https://avatars.githubusercontent.com/u/4223?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/rails",
        html_url: "https://github.com/rails",
        followers_url: "https://api.github.com/users/rails/followers",
        following_url:
          "https://api.github.com/users/rails/following{/other_user}",
        gists_url: "https://api.github.com/users/rails/gists{/gist_id}",
        starred_url:
          "https://api.github.com/users/rails/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/rails/subscriptions",
        organizations_url: "https://api.github.com/users/rails/orgs",
        repos_url: "https://api.github.com/users/rails/repos",
        events_url: "https://api.github.com/users/rails/events{/privacy}",
        received_events_url:
          "https://api.github.com/users/rails/received_events",
        type: "Organization",
        site_admin: false,
      },
      html_url: "https://github.com/rails/rails",
      description: "Ruby on Rails",
      fork: false,
      url: "https://api.github.com/repos/rails/rails",
      forks_url: "https://api.github.com/repos/rails/rails/forks",
      keys_url: "https://api.github.com/repos/rails/rails/keys{/key_id}",
      collaborators_url:
        "https://api.github.com/repos/rails/rails/collaborators{/collaborator}",
      teams_url: "https://api.github.com/repos/rails/rails/teams",
      hooks_url: "https://api.github.com/repos/rails/rails/hooks",
      issue_events_url:
        "https://api.github.com/repos/rails/rails/issues/events{/number}",
      events_url: "https://api.github.com/repos/rails/rails/events",
      assignees_url:
        "https://api.github.com/repos/rails/rails/assignees{/user}",
      branches_url:
        "https://api.github.com/repos/rails/rails/branches{/branch}",
      tags_url: "https://api.github.com/repos/rails/rails/tags",
      blobs_url: "https://api.github.com/repos/rails/rails/git/blobs{/sha}",
      git_tags_url: "https://api.github.com/repos/rails/rails/git/tags{/sha}",
      git_refs_url: "https://api.github.com/repos/rails/rails/git/refs{/sha}",
      trees_url: "https://api.github.com/repos/rails/rails/git/trees{/sha}",
      statuses_url: "https://api.github.com/repos/rails/rails/statuses/{sha}",
      languages_url: "https://api.github.com/repos/rails/rails/languages",
      stargazers_url: "https://api.github.com/repos/rails/rails/stargazers",
      contributors_url: "https://api.github.com/repos/rails/rails/contributors",
      subscribers_url: "https://api.github.com/repos/rails/rails/subscribers",
      subscription_url: "https://api.github.com/repos/rails/rails/subscription",
      commits_url: "https://api.github.com/repos/rails/rails/commits{/sha}",
      git_commits_url:
        "https://api.github.com/repos/rails/rails/git/commits{/sha}",
      comments_url:
        "https://api.github.com/repos/rails/rails/comments{/number}",
      issue_comment_url:
        "https://api.github.com/repos/rails/rails/issues/comments{/number}",
      contents_url: "https://api.github.com/repos/rails/rails/contents/{+path}",
      compare_url:
        "https://api.github.com/repos/rails/rails/compare/{base}...{head}",
      merges_url: "https://api.github.com/repos/rails/rails/merges",
      archive_url:
        "https://api.github.com/repos/rails/rails/{archive_format}{/ref}",
      downloads_url: "https://api.github.com/repos/rails/rails/downloads",
      issues_url: "https://api.github.com/repos/rails/rails/issues{/number}",
      pulls_url: "https://api.github.com/repos/rails/rails/pulls{/number}",
      milestones_url:
        "https://api.github.com/repos/rails/rails/milestones{/number}",
      notifications_url:
        "https://api.github.com/repos/rails/rails/notifications{?since,all,participating}",
      labels_url: "https://api.github.com/repos/rails/rails/labels{/name}",
      releases_url: "https://api.github.com/repos/rails/rails/releases{/id}",
      deployments_url: "https://api.github.com/repos/rails/rails/deployments",
      created_at: "2008-04-11T02:19:47Z",
      updated_at: "2022-01-26T19:41:01Z",
      pushed_at: "2022-01-26T19:31:17Z",
      git_url: "git://github.com/rails/rails.git",
      ssh_url: "git@github.com:rails/rails.git",
      clone_url: "https://github.com/rails/rails.git",
      svn_url: "https://github.com/rails/rails",
      homepage: "https://rubyonrails.org",
      size: 241151,
      stargazers_count: 49999,
      watchers_count: 49999,
      language: "Ruby",
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      forks_count: 20072,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 601,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
        node_id: "MDc6TGljZW5zZTEz",
      },
      allow_forking: true,
      is_template: false,
      topics: [
        "activejob",
        "activerecord",
        "framework",
        "html",
        "mvc",
        "rails",
        "ruby",
      ],
      visibility: "public",
      forks: 20072,
      open_issues: 601,
      watchers: 49999,
      default_branch: "main",
    },
  },
  _links: {
    self: {
      href: "https://api.github.com/repos/rails/rails/pulls/44213",
    },
    html: {
      href: "https://github.com/rails/rails/pull/44213",
    },
    issue: {
      href: "https://api.github.com/repos/rails/rails/issues/44213",
    },
    comments: {
      href: "https://api.github.com/repos/rails/rails/issues/44213/comments",
    },
    review_comments: {
      href: "https://api.github.com/repos/rails/rails/pulls/44213/comments",
    },
    review_comment: {
      href: "https://api.github.com/repos/rails/rails/pulls/comments{/number}",
    },
    commits: {
      href: "https://api.github.com/repos/rails/rails/pulls/44213/commits",
    },
    statuses: {
      href: "https://api.github.com/repos/rails/rails/statuses/a9d3bb1a3bd0a30f7d6fe25b6eda3ebf3ca3cd8c",
    },
  },
  author_association: "CONTRIBUTOR",
  auto_merge: null,
  active_lock_reason: null,
  merged: false,
  mergeable: true,
  rebaseable: true,
  mergeable_state: "clean",
  merged_by: null,
  comments: 9,
  review_comments: 4,
  maintainer_can_modify: true,
  commits: 3,
  additions: 48,
  deletions: 1,
  changed_files: 2,
};
const comments = [
  {
    url: "https://api.github.com/repos/rails/rails/pulls/comments/788954337",
    pull_request_review_id: 858526065,
    id: 788954337,
    node_id: "PRRC_kwDNIULOLwZ84Q",
    diff_hunk:
      "@@ -138,7 +144,14 @@ def as_json(options = nil) # :nodoc:\n \n module Enumerable\n   def as_json(options = nil) # :nodoc:\n-    to_a.as_json(options)\n+    respond_to = Kernel.instance_method(:respond_to?).bind(self)",
    path: "activesupport/lib/active_support/core_ext/object/json.rb",
    position: null,
    original_position: 18,
    commit_id: "a9d3bb1a3bd0a30f7d6fe25b6eda3ebf3ca3cd8c",
    original_commit_id: "90788d2aaf96c2d80f393309bf3cedcef36fd2b1",
    user: {
      login: "casperisfine",
      id: 19192189,
      node_id: "MDQ6VXNlcjE5MTkyMTg5",
      avatar_url: "https://avatars.githubusercontent.com/u/19192189?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/casperisfine",
      html_url: "https://github.com/casperisfine",
      followers_url: "https://api.github.com/users/casperisfine/followers",
      following_url:
        "https://api.github.com/users/casperisfine/following{/other_user}",
      gists_url: "https://api.github.com/users/casperisfine/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/casperisfine/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/casperisfine/subscriptions",
      organizations_url: "https://api.github.com/users/casperisfine/orgs",
      repos_url: "https://api.github.com/users/casperisfine/repos",
      events_url: "https://api.github.com/users/casperisfine/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/casperisfine/received_events",
      type: "User",
      site_admin: false,
    },
    body: "`Kernel.instance_method(:respond_to?)` instantiate a new `UnboundMethod` on each call, it could be constantized.\r\n\r\nThen `bind(self)` instantiate a `Method`, you could use `bind_call` instead.",
    created_at: "2022-01-20T16:46:42Z",
    updated_at: "2022-01-20T16:48:11Z",
    html_url: "https://github.com/rails/rails/pull/44213#discussion_r788954337",
    pull_request_url: "https://api.github.com/repos/rails/rails/pulls/44213",
    author_association: "CONTRIBUTOR",
    _links: {
      self: {
        href: "https://api.github.com/repos/rails/rails/pulls/comments/788954337",
      },
      html: {
        href: "https://github.com/rails/rails/pull/44213#discussion_r788954337",
      },
      pull_request: {
        href: "https://api.github.com/repos/rails/rails/pulls/44213",
      },
    },
    reactions: {
      url: "https://api.github.com/repos/rails/rails/pulls/comments/788954337/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    start_line: null,
    original_start_line: null,
    start_side: null,
    line: null,
    original_line: 147,
    side: "RIGHT",
  },
  {
    url: "https://api.github.com/repos/rails/rails/pulls/comments/788954951",
    pull_request_review_id: 858526065,
    id: 788954951,
    node_id: "PRRC_kwDNIULOLwZ_Rw",
    diff_hunk:
      "@@ -59,6 +59,12 @@ class Object\n   def as_json(options = nil) # :nodoc:\n     if respond_to?(:to_hash)\n       to_hash.as_json(options)\n+    elsif respond_to?(:to_ary)\n+      to_ary.as_json(options)\n+    elsif respond_to?(:to_str)\n+      to_str.as_json(options)\n+    elsif respond_to?(:to_int)\n+      to_int.as_json(options)",
    path: "activesupport/lib/active_support/core_ext/object/json.rb",
    position: 9,
    original_position: 9,
    commit_id: "a9d3bb1a3bd0a30f7d6fe25b6eda3ebf3ca3cd8c",
    original_commit_id: "90788d2aaf96c2d80f393309bf3cedcef36fd2b1",
    user: {
      login: "casperisfine",
      id: 19192189,
      node_id: "MDQ6VXNlcjE5MTkyMTg5",
      avatar_url: "https://avatars.githubusercontent.com/u/19192189?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/casperisfine",
      html_url: "https://github.com/casperisfine",
      followers_url: "https://api.github.com/users/casperisfine/followers",
      following_url:
        "https://api.github.com/users/casperisfine/following{/other_user}",
      gists_url: "https://api.github.com/users/casperisfine/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/casperisfine/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/casperisfine/subscriptions",
      organizations_url: "https://api.github.com/users/casperisfine/orgs",
      repos_url: "https://api.github.com/users/casperisfine/repos",
      events_url: "https://api.github.com/users/casperisfine/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/casperisfine/received_events",
      type: "User",
      site_admin: false,
    },
    body: "All these extra checks are quire costly. Would be worth benching this with benchmark/ips to see what's the overhead is like.",
    created_at: "2022-01-20T16:47:20Z",
    updated_at: "2022-01-20T16:48:11Z",
    html_url: "https://github.com/rails/rails/pull/44213#discussion_r788954951",
    pull_request_url: "https://api.github.com/repos/rails/rails/pulls/44213",
    author_association: "CONTRIBUTOR",
    _links: {
      self: {
        href: "https://api.github.com/repos/rails/rails/pulls/comments/788954951",
      },
      html: {
        href: "https://github.com/rails/rails/pull/44213#discussion_r788954951",
      },
      pull_request: {
        href: "https://api.github.com/repos/rails/rails/pulls/44213",
      },
    },
    reactions: {
      url: "https://api.github.com/repos/rails/rails/pulls/comments/788954951/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    start_line: 62,
    original_start_line: 62,
    start_side: "RIGHT",
    line: 67,
    original_line: 67,
    side: "RIGHT",
  },
  {
    url: "https://api.github.com/repos/rails/rails/pulls/comments/790118395",
    pull_request_review_id: 860183634,
    id: 790118395,
    node_id: "PRRC_kwDNIULOLxg_-w",
    diff_hunk:
      "@@ -138,7 +144,14 @@ def as_json(options = nil) # :nodoc:\n \n module Enumerable\n   def as_json(options = nil) # :nodoc:\n-    to_a.as_json(options)\n+    respond_to = Kernel.instance_method(:respond_to?).bind(self)",
    path: "activesupport/lib/active_support/core_ext/object/json.rb",
    position: null,
    original_position: 18,
    commit_id: "a9d3bb1a3bd0a30f7d6fe25b6eda3ebf3ca3cd8c",
    original_commit_id: "90788d2aaf96c2d80f393309bf3cedcef36fd2b1",
    user: {
      login: "notEthan",
      id: 133719,
      node_id: "MDQ6VXNlcjEzMzcxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/133719?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/notEthan",
      html_url: "https://github.com/notEthan",
      followers_url: "https://api.github.com/users/notEthan/followers",
      following_url:
        "https://api.github.com/users/notEthan/following{/other_user}",
      gists_url: "https://api.github.com/users/notEthan/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/notEthan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/notEthan/subscriptions",
      organizations_url: "https://api.github.com/users/notEthan/orgs",
      repos_url: "https://api.github.com/users/notEthan/repos",
      events_url: "https://api.github.com/users/notEthan/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/notEthan/received_events",
      type: "User",
      site_admin: false,
    },
    body: "thanks ",
    created_at: "2022-01-22T08:22:59Z",
    updated_at: "2022-01-22T08:22:59Z",
    html_url: "https://github.com/rails/rails/pull/44213#discussion_r790118395",
    pull_request_url: "https://api.github.com/repos/rails/rails/pulls/44213",
    author_association: "CONTRIBUTOR",
    _links: {
      self: {
        href: "https://api.github.com/repos/rails/rails/pulls/comments/790118395",
      },
      html: {
        href: "https://github.com/rails/rails/pull/44213#discussion_r790118395",
      },
      pull_request: {
        href: "https://api.github.com/repos/rails/rails/pulls/44213",
      },
    },
    reactions: {
      url: "https://api.github.com/repos/rails/rails/pulls/comments/790118395/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    start_line: null,
    original_start_line: null,
    start_side: null,
    line: null,
    original_line: 147,
    side: "RIGHT",
    in_reply_to_id: 788954337,
  },
  {
    url: "https://api.github.com/repos/rails/rails/pulls/comments/790131020",
    pull_request_review_id: 860195471,
    id: 790131020,
    node_id: "PRRC_kwDNIULOLxhxTA",
    diff_hunk:
      "@@ -136,9 +142,17 @@ def as_json(options = nil) # :nodoc:\n   end\n end\n \n+ActiveSupport::KERNEL_RESPOND_TO = Kernel.instance_method(:respond_to?)",
    path: "activesupport/lib/active_support/core_ext/object/json.rb",
    position: 17,
    original_position: 17,
    commit_id: "a9d3bb1a3bd0a30f7d6fe25b6eda3ebf3ca3cd8c",
    original_commit_id: "a9d3bb1a3bd0a30f7d6fe25b6eda3ebf3ca3cd8c",
    user: {
      login: "notEthan",
      id: 133719,
      node_id: "MDQ6VXNlcjEzMzcxOQ==",
      avatar_url: "https://avatars.githubusercontent.com/u/133719?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/notEthan",
      html_url: "https://github.com/notEthan",
      followers_url: "https://api.github.com/users/notEthan/followers",
      following_url:
        "https://api.github.com/users/notEthan/following{/other_user}",
      gists_url: "https://api.github.com/users/notEthan/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/notEthan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/notEthan/subscriptions",
      organizations_url: "https://api.github.com/users/notEthan/orgs",
      repos_url: "https://api.github.com/users/notEthan/repos",
      events_url: "https://api.github.com/users/notEthan/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/notEthan/received_events",
      type: "User",
      site_admin: false,
    },
    body: "I wasn't sure the best place to put this (either in terms of namespace or location in the code). feedback welcome.",
    created_at: "2022-01-22T11:03:11Z",
    updated_at: "2022-01-22T11:03:11Z",
    html_url: "https://github.com/rails/rails/pull/44213#discussion_r790131020",
    pull_request_url: "https://api.github.com/repos/rails/rails/pulls/44213",
    author_association: "CONTRIBUTOR",
    _links: {
      self: {
        href: "https://api.github.com/repos/rails/rails/pulls/comments/790131020",
      },
      html: {
        href: "https://github.com/rails/rails/pull/44213#discussion_r790131020",
      },
      pull_request: {
        href: "https://api.github.com/repos/rails/rails/pulls/44213",
      },
    },
    reactions: {
      url: "https://api.github.com/repos/rails/rails/pulls/comments/790131020/reactions",
      total_count: 0,
      "+1": 0,
      "-1": 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    start_line: null,
    original_start_line: null,
    start_side: null,
    line: 145,
    original_line: 145,
    side: "RIGHT",
  },
];

while (!$) {
  console.log("no $");
}
$(document).ready(function () {
  let pr = $("#ghHolder").append(`
    <details>
    <summary>${prJson.title}</summary>
    </details>`);
  console.log(pr);
  comments.forEach((comment) => {
    pr.append(`<div>
  <div>
  <p class="comment-poster">${comment.user.login}</p>
  <p class="comment-date">${comment.created_at}</p>
</div>
<p class="comment-body">${comment.body}</p>
  </div>`);
  });
});
